# Generated by Django 3.0.6 on 2020-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200518_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roba',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
