# Generated by Django 3.0.6 on 2020-05-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200519_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorija',
            name='asortiman',
        ),
        migrations.RemoveField(
            model_name='roba',
            name='kategorija',
        ),
        migrations.DeleteModel(
            name='Asortiman',
        ),
        migrations.DeleteModel(
            name='Kategorija',
        ),
    ]
