# Generated by Django 3.0.6 on 2020-05-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200519_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roba',
            new_name='m_odjeca',
        ),
    ]
