# Generated by Django 3.0.6 on 2020-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_d_obuca_d_odjeca_d_oprema_m_obuca_m_oprema_z_obuca_z_odjeca_z_oprema'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_obuca',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='d_odjeca',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='d_oprema',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_obuca',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_odjeca',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_oprema',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z_obuca',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z_odjeca',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='z_oprema',
            name='korpa',
            field=models.BooleanField(default=False),
        ),
    ]
